# Production release: van; Kubernetes context: ectobit; namespace: repo.
image:
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "false"
    cert-manager.io/cluster-issuer: acme-issuer
  hosts:
  - host: go.acim.net
    paths:
    - path: /
      pathType: ImplementationSpecific
  - host: go.ectobit.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: van-tls
    hosts:
    - go.acim.net
    - go.ectobit.com
config:
  go.acim.net/bee: https://github.com/acim/bee
  go.acim.net/bus: https://github.com/acim/bus
  go.acim.net/cog: https://github.com/acim/cog
  go.acim.net/gap: https://github.com/acim/gap
  go.acim.net/hcdns: https://github.com/acim/hcdns
  go.acim.net/mig: https://github.com/acim/mig
  go.acim.net/quota: https://github.com/acim/quota
  go.acim.net/van: https://github.com/acim/van
